{
 "title": "DHCP Activity",
 "tags": [ "network-monitor" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "pool",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "DHCP Events (24h)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count_over_time({job=\"vector-lmserver\"} | json | appname=~\"dhcp.*\" [$__range])"
    }
   ]
  },
  {
   "title": "Assignments (24h)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count_over_time({job=\"vector-lmserver\"} | json | appname=~\"dhcp.*\" | message=~\"assigned.*\" | message!~\"deassigned.*\" [$__range])"
    }
   ]
  },
  {
   "title": "Deassignments (24h)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count_over_time({job=\"vector-lmserver\"} | json | appname=~\"dhcp.*\" |= \"deassigned\" [$__range])"
    }
   ]
  },
  {
   "title": "Unique MACs (24h)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(count_over_time({job=\"vector-lmserver\"} | json | appname=~\"dhcp.*\" | pattern `<action> <ip> for <mac>` | keep mac [$__range]) by (mac))"
    }
   ]
  },
  {
   "title": "DHCP Event Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"vector-lmserver\"} | json | appname=~\"dhcp.*\" | message=~\"assigned.*\" | message!~\"deassigned.*\" [$__auto]))",
     "legendFormat": "Assigned"
    },
    {
     "expr": "sum(count_over_time({job=\"vector-lmserver\"} | json | appname=~\"dhcp.*\" |= \"deassigned\" [$__auto]))",
     "legendFormat": "Deassigned"
    }
   ]
  },
  {
   "title": "Events by DHCP Pool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum by (appname) (count_over_time({job=\"vector-lmserver\"} | json | appname=~\"${pool:regex}\" [$__auto]))",
     "legendFormat": "{{appname}}"
    }
   ]
  },
  {
   "title": "Top Devices by DHCP Churn",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "topk(10, count_over_time({job=\"vector-lmserver\"} | json | appname=~\"dhcp.*\" | pattern `<action> <ip> for <mac>` | keep mac [$__range]) by (mac))"
    }
   ]
  },
  {
   "title": "DHCP Event Log",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "{job=\"vector-lmserver\"} | json | appname=~\"${pool:regex}\""
    }
   ]
  }
 ]
}